// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUfB9ZvclVUlX_q4YUbO-X6zUKYutMHSk',
    appId: '1:524908255320:web:e2ba1ca83720e2ee96122d',
    messagingSenderId: '524908255320',
    projectId: 'temp-49dae',
    authDomain: 'temp-49dae.firebaseapp.com',
    databaseURL: 'https://temp-49dae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'temp-49dae.appspot.com',
    measurementId: 'G-E73Q20NV7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZC2anMVWDjXX1SQuLFyf-fqmam-amDYM',
    appId: '1:524908255320:android:7b41d317d87e69da96122d',
    messagingSenderId: '524908255320',
    projectId: 'temp-49dae',
    databaseURL: 'https://temp-49dae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'temp-49dae.appspot.com',
  );
}
